# Dogs vs Cats Classification

This is an image classification task of classifying dogs and cats. <br />
Dataset can be downloaded from [here](https://www.kaggle.com/c/dogs-vs-cats/data) <br />
Please split dataset (both cat & dog label) into different folders, take the 1st 10k images of each label to train and the rest go to validation. <br />

In [1]:
import os, glob
import numpy as np
import pandas as pd
from PIL import Image
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from keras.preprocessing.image import load_img
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense
from keras.optimizers import SGD

Using TensorFlow backend.


In [2]:
train_images = []
train_classes = []
i = 0
for filename in os.listdir("train_sliced/"):
    img = load_img("train_sliced/"+filename, target_size=(150,150))
    img = np.array(img)
#     img = np.expand_dims(img, axis=0)
    train_images.append(img)
    train_classes.append(filename.split(".")[0])
    i += 1
    if i % 500 == 0:
        print(i, filename, img.shape, filename.split(".")[0])

500 cat.1447.jpg (150, 150, 3) cat
1000 cat.1898.jpg (150, 150, 3) cat
1500 cat.2347.jpg (150, 150, 3) cat
2000 cat.2798.jpg (150, 150, 3) cat
2500 cat.3247.jpg (150, 150, 3) cat
3000 cat.3698.jpg (150, 150, 3) cat
3500 cat.4147.jpg (150, 150, 3) cat
4000 cat.4598.jpg (150, 150, 3) cat
4500 cat.548.jpg (150, 150, 3) cat
5000 cat.999.jpg (150, 150, 3) cat
5500 dog.1447.jpg (150, 150, 3) dog
6000 dog.1898.jpg (150, 150, 3) dog
6500 dog.2347.jpg (150, 150, 3) dog
7000 dog.2798.jpg (150, 150, 3) dog
7500 dog.3247.jpg (150, 150, 3) dog
8000 dog.3698.jpg (150, 150, 3) dog
8500 dog.4147.jpg (150, 150, 3) dog
9000 dog.4598.jpg (150, 150, 3) dog
9500 dog.548.jpg (150, 150, 3) dog
10000 dog.999.jpg (150, 150, 3) dog


In [3]:
val_images = []
val_classes = []
i = 0
for filename in os.listdir("validation_sliced/"):
    img = load_img("validation_sliced/"+filename, target_size=(150,150))
    img = np.array(img)
#     img = np.expand_dims(img, axis=0)
    val_images.append(img)
    val_classes.append(filename.split(".")[0])
    i += 1
    if i % 500 == 0:
        print(i, filename, img.shape, filename.split(".")[0])

500 cat.10499.jpg (150, 150, 3) cat
1000 cat.10999.jpg (150, 150, 3) cat
1500 cat.11499.jpg (150, 150, 3) cat
2000 cat.11999.jpg (150, 150, 3) cat
2500 dog.10499.jpg (150, 150, 3) dog
3000 dog.10999.jpg (150, 150, 3) dog
3500 dog.11499.jpg (150, 150, 3) dog
4000 dog.11999.jpg (150, 150, 3) dog


In [4]:
le = LabelEncoder()
train_labels = np.expand_dims(le.fit_transform(train_classes), axis=1)
val_labels = np.expand_dims(le.fit_transform(val_classes), axis=1)

train_labels = to_categorical(train_labels)
val_labels = to_categorical(val_labels)

In [5]:
train_images = np.array(train_images)
val_images = np.array(val_images)

In [6]:
train_labels[0], val_labels[0]

(array([1., 0.], dtype=float32), array([1., 0.], dtype=float32))

In [7]:
train_images[0]

array([[[203, 164,  87],
        [209, 170,  93],
        [209, 170,  93],
        ...,
        [247, 206, 124],
        [244, 204, 119],
        [240, 201, 122]],

       [[203, 164,  87],
        [209, 170,  93],
        [209, 170,  93],
        ...,
        [245, 207, 124],
        [245, 204, 122],
        [240, 201, 122]],

       [[203, 164,  87],
        [209, 170,  93],
        [209, 170,  93],
        ...,
        [247, 209, 128],
        [244, 206, 125],
        [242, 203, 124]],

       ...,

       [[158, 124,  53],
        [159, 125,  54],
        [160, 126,  55],
        ...,
        [  3,   4,   0],
        [  3,   4,   0],
        [  2,   2,   0]],

       [[154, 123,  56],
        [155, 124,  57],
        [158, 127,  60],
        ...,
        [  2,   2,   0],
        [  2,   2,   0],
        [  2,   2,   0]],

       [[152, 121,  54],
        [153, 122,  55],
        [157, 126,  59],
        ...,
        [  2,   2,   0],
        [  2,   2,   0],
        [  2,   2,   0]]

In [8]:
train_images = train_images.astype("float32")/255
val_images = val_images.astype("float32")/255

In [9]:
train_images[0]

array([[[0.79607844, 0.6431373 , 0.34117648],
        [0.81960785, 0.6666667 , 0.3647059 ],
        [0.81960785, 0.6666667 , 0.3647059 ],
        ...,
        [0.96862745, 0.80784315, 0.4862745 ],
        [0.95686275, 0.8       , 0.46666667],
        [0.9411765 , 0.7882353 , 0.47843137]],

       [[0.79607844, 0.6431373 , 0.34117648],
        [0.81960785, 0.6666667 , 0.3647059 ],
        [0.81960785, 0.6666667 , 0.3647059 ],
        ...,
        [0.9607843 , 0.8117647 , 0.4862745 ],
        [0.9607843 , 0.8       , 0.47843137],
        [0.9411765 , 0.7882353 , 0.47843137]],

       [[0.79607844, 0.6431373 , 0.34117648],
        [0.81960785, 0.6666667 , 0.3647059 ],
        [0.81960785, 0.6666667 , 0.3647059 ],
        ...,
        [0.96862745, 0.81960785, 0.5019608 ],
        [0.95686275, 0.80784315, 0.49019608],
        [0.9490196 , 0.79607844, 0.4862745 ]],

       ...,

       [[0.61960787, 0.4862745 , 0.20784314],
        [0.62352943, 0.49019608, 0.21176471],
        [0.627451  , 0

In [10]:
model = Sequential()
model.add(Conv2D(128, (3,3), activation="relu", input_shape=(150,150,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.3))
model.add(Conv2D(64, (3,3), activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.3))
model.add(Flatten())
model.add(Dense(32, activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(2, activation="sigmoid"))

model.compile(optimizer=SGD(lr=0.002, momentum=0.8), loss="binary_crossentropy", metrics=["accuracy"])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 148, 148, 128)     3584      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 74, 74, 128)       0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 74, 74, 128)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 72, 72, 64)        73792     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 36, 36, 64)        0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 36, 36, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 82944)            

In [14]:
history = model.fit(train_images, train_labels, validation_data=(val_images, val_labels), epochs=10, batch_size=16, verbose=1)

Train on 10000 samples, validate on 4000 samples
Epoch 1/10
10000/10000 [==============================] - 1118s 112ms/step - loss: 0.6908 - accuracy: 0.5246 - val_loss: 0.6889 - val_accuracy: 0.5429
Epoch 2/10
10000/10000 [==============================] - 1124s 112ms/step - loss: 0.6855 - accuracy: 0.5470 - val_loss: 0.6823 - val_accuracy: 0.5552
Epoch 3/10
10000/10000 [==============================] - 1157s 116ms/step - loss: 0.6781 - accuracy: 0.5640 - val_loss: 0.6721 - val_accuracy: 0.6055
Epoch 4/10
10000/10000 [==============================] - 1108s 111ms/step - loss: 0.6692 - accuracy: 0.5833 - val_loss: 0.6599 - val_accuracy: 0.6234
Epoch 5/10
10000/10000 [==============================] - 798s 80ms/step - loss: 0.6558 - accuracy: 0.6039 - val_loss: 0.6631 - val_accuracy: 0.6265
Epoch 6/10
10000/10000 [==============================] - 880s 88ms/step - loss: 0.6423 - accuracy: 0.6177 - val_loss: 0.6597 - val_accuracy: 0.5857
Epoch 7/10
10000/10000 [=========================